services:
    builder:
        # Docker container for building the code.
        build:
            context: .
            dockerfile: dockerfiles/ros_env.docker
            target: builder
            args:
                # Force the user in the container to have the same UID to avoid permission issues.
                ROS_UID: "${ROS_UID}"
                # Public key used for key-only SSH login in the builder image.
                ROS_SSH_PUBLIC_KEY: "${ROS_SSH_PUBLIC_KEY}"
        ports:
            - "1825:22"
        profiles:
            - dev
        volumes:
            - .:/home/ros/ros_libcamera
            # Allow us to use existing SSH keys when copying to the robot.
            - ~/.ssh/id_rsa:/home/ros/.ssh/id_rsa

    ros:
        # Docker container for running ros.
        image: ros:noetic-ros-core
        command: roscore
        ports:
            - "11311:11311"
        profiles:
            - visualize
            - extract_videos

    rviz:
        # Docker container for running rviz.
        build:
            context: .
            dockerfile: dockerfiles/ros_env.docker
            target: rviz
        profiles:
            - visualize
        volumes:
            # Share the host's X server.
            - ~/.Xauthority:/root/.Xauthority
            - /tmp/.X11-unix:/tmp/.X11-unix
            # Share the GPU.
            - /dev:/dev
        environment:
            # Share the display.
            DISPLAY: ${DISPLAY}
            # Because we have to run on the host network for X11 to work, we need
            # to point it to the exported ROS master port.
            ROS_MASTER_URI: "http://localhost:11311"
        command: /rviz.sh
        network_mode: host

    reconfigure:
        # Docker container for running rqt_reconfigure.
        build:
            context: .
            dockerfile: dockerfiles/ros_env.docker
            target: reconfigure
        profiles:
            - visualize
        volumes:
            # Share the host's X server.
            - ~/.Xauthority:/root/.Xauthority
            - /tmp/.X11-unix:/tmp/.X11-unix
            # Share the GPU.
            - /dev:/dev
        environment:
            # Share the display.
            DISPLAY: ${DISPLAY}
            # Because we have to run on the host network for X11 to work, we need
            # to point it to the exported ROS master port.
            ROS_MASTER_URI: "http://localhost:11311"
        command: /rqt_reconfigure.sh
        network_mode: host

    extract_videos:
        # Docker container for extracting videos.
        build:
            context: .
            dockerfile: dockerfiles/ros_env.docker
            target: video_extractor
            args:
                # Force the user in the container to have the same UID to avoid permission issues.
                ROS_UID: "${ROS_UID}"
                # Public key used for SSH login in the builder stage.
                ROS_SSH_PUBLIC_KEY: "${ROS_SSH_PUBLIC_KEY}"
        profiles:
            - extract_videos
        environment:
            ROS_MASTER_URI: "http://localhost:11311"
            LD_LIBRARY_PATH: "$${LD_LIBRARY_PATH}:/usr/local/lib/"
            BAG_FILE: "${BAG_FILE}"
            EXTRA_ARGS: "${EXTRA_ARGS:-}"
        command: bash -c "cd /home/ros/ros_libcamera && source devel/setup.bash && python3 extract_videos.py /host/$${BAG_FILE} $${EXTRA_ARGS}"
        volumes:
            - /:/host
            # Use this to speed up FS operations. We don't use a tmpfs mount because Docker
            # backs those with RAM, and we might need to write a LOT of data.
            - /tmp:/tmp
